создаёт page-header
htmlacademy-htmlcss/2101121-sedona-34 pull request #2
Opened 2022-05-21 13:48 UTC by Danilooo77

немного не понял навигацию сайта и где использовать ссылки а где кнопку

2022-05-22 10:05 UTC, Kartaviy-arteom requested changes

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +        <ul class="navigation-list">
Здесь и далее необходимо соблюдать вложенность, так же  обрати внимание на написание alt текста у картинки, в учебнике это здесь https://htmlacademy.ru/blog/articles/alt-text

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +          <ul class="navigation-user">
Здесь я не совсем понял для чего тебе такой же класс как и у списка выше, но можно пока оставить. При написании стилей это будет понятнее. По поводу использования списка в данном месте, несколько спорно, но можно впринципе и оставить.

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +              <a class="navigation-link" href="#">Хочу сюда</a></li>
Я думаю в  первой li это опечатка, имелась в виду ссылка внутри, не кнопка. Обрати, пожалуйста, внимание на отступы.

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +      <main class="main-ndex">
header и main находятся на одном уровне вложенности, у них должен быть одинаковый отступ

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +      </main>
в данном проекте ты вкладываешь в основное содержание страницы все секции до футера

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +            <span>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</span>
p здесь подошел бы больше

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +            </ul>
тут я не совсем согласен. По сути у нас с тобой есть список из 5 причин. внутри причины могут содержать несколько карточек или другой контент

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +          <h2 class="register-tour-title">Заинтересовались? </h2>
заголовок не отображает суть, лучше добавить скрытый заголовок. А "заинтересовались" отобразить в другом теге

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +          <button class="register-tour-button" type="button"><span class="register-tour-button-info">Поиск гостиницы в седоне</span></button>
уместней будет ссылка для открытия этой модалки

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +                <input class="field" placeholder="Ваш e-mail" type="email" name="newsletter-email" required>
нужно добавить label для input https://up.htmlacademy.ru/htmlcss/34/criteries#HTML

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +         <section class="footer-social">
для section рекомендуется использовать заголовок

2022-05-22 10:05 UTC, Kartaviy-arteom commented on index.html
> +          <p class="about-text>"><a class="htmlacademy-link" href="https://htmlacademy.ru">.html academy</a></p>
для логотипов, которые даже текст, нужно использовать картинку, это связано с отображением и загрузкой шрифтов на странице. В макете там есть картинка, которая будет обернута в ссылку. Можно добавить ей (ссылке) атрибут target="_blank", чтобы ссылка открылась в новой странице.

2022-05-22 18:34 UTC, Danilooo77 commented on index.html
> +              <a class="navigation-link" href="#">Хочу сюда</a></li>
![image](https://user-images.githubusercontent.com/105683318/169710400-e49a0ffe-5ece-46e6-8e37-6398158b52ac.png)
разве "поиск" это ссылка а не кнопа?

2022-05-24 12:40 UTC, Kartaviy-arteom approved these changes

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> -    <meta charset="utf-8">
кодировка нужна

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +      <a class="header-ikon" href="index.html">
Думаю это опечатка, но header-i**c**on

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +        <img class="header-ikon" src="#" alt="city of seddona"></a>
не уверен что этот класс тебе пригодится, ты используешь такой же на ссылке.

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +      <p class="advantages-logo">
меня смущает этот не закрытый параграф, так как он открыт код не валиден и не понятно для чего он тут

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +            <p class="advantages-description"> Седона — не аттракцион для туристов, там течёт своя жизнь </p>
тебе пригодится обернуть это в div, для группировки, не для семантики, как и для плиток далее

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +            <p class="advantages-description">Да, по нему можно пройти! Если вы осмелитесь, разумеется </p>
тут тоже сгрупировать

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +      <h2 class="register-tour-title">Заинтересовались? </h2>
у тебя один заголовок уровня h2, заинтересовались может быть strong,b, div ...

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +      <a class="register-tour-button" type="button"><span class="register-tour-button-info">Поиск гостиницы в
если это ссылка type не нужен, type это тип у кнопки

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +        </label>
visually-hidden это распространенный паттерн, внутри обычно такие стили
`.visually-hidden {
  position: absolute;
  white-space: nowrap;
  width: 1px;
  height: 1px;
  overflow: hidden;
  border: 0;
  padding: 0;
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
  margin: -1px;
}`

- Назначая этот класс, ты скроешь и его дочерние, т.е и сам input. Так же в label сейчас нет подписи к элементу

2022-05-24 12:40 UTC, Kartaviy-arteom commented on index.html
> +      </li>
с первого раза трудно быть уверенным, что спан внутри ссылки, а не лежит рядом.

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="button-reset" type="submit">Сбросить</button>
есть button type reset https://developer.mozilla.org/ru/docs/Web/HTML/Element/button

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +            <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
ты наверное пропустил группу тип жилья

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +                            </label>
для стилизация чекбоксов тебе будет удобнее связать через id

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +            <h2 class="quantity-hotel">Найдено гостиниц: 38</h2>
не думаю что это похоже на заголовок

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +            <fieldset class="catalog-filter-group">
fieldset это про набор полей формы, тут он вне формы

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +                <ul class="catalog-filter-list">
а это из формы выше

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +                    <span class="rating rating-star"><span class="visually-hidden">звёздочки</span></span>
звездочки можно сделать например, добавляя в обертку кол-во элементов по кол-ву звездочек.

2022-05-24 12:40 UTC, Kartaviy-arteom commented on catalog.html
> +            </label>
думаю это select

2022-05-24 12:41 UTC, Kartaviy-arteom commented
я добавил ряд комментариев, будет необходимо внести ряд правок в начале следующего задания

2022-05-24 12:42 UTC, merged