add font weight for index
htmlacademy-htmlcss/2101121-sedona-34 pull request #4
Opened 2022-06-01 19:02 UTC by Danilooo77

2022-06-02 06:43 UTC, Kartaviy-arteom requested changes

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
>    background-color: #fbf7f4;
что-то я не увидел от куда этот цвет

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
чаще все-таки просто в контенте будет просто первая буква заглавная

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
>  a.broun {
Если это только кнопка из хедера там еще uppercase и др font-size и line-height

2022-06-02 06:43 UTC, Kartaviy-arteom commented on index.html
>        alt="логотип туристической агении Приветствуем в Седона на фоне гор">
Лучше будет сгруппировать первые два элемента и повесить первый фон на группирующий тег

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding-left: 290px;
если padding-left нужен для выравнивания по центру - это не тот способ

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  text-align: center;
Если значение 0, обычно не ставят единицы измерения. 0px=>0
Для выравнивания можно попробовать
display: block;
max-width: 620px;
margin: 0 auto;

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding-top: -11px;
некорректное значение, не может быть отрицательным

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 103px 85px 0px 85px;
я бы не оставлял ей нижний padding=0, при изменении контента может текст дойти до нижней границы

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background-image: url("../images/background.jpg") ;
лучше этот фон повесить на другой элемент, тут от добавит тебе проблем

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding:94px 398px 29px;
это не то, что тебе нужно

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  display: inline-block;
для чего здесь inline-block?

2022-06-02 06:43 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 0px 0px 0px 20px;
border-radius: 10px 0 0 10px;
padding: 0 0 0 20px;

2022-06-03 19:46 UTC, Kartaviy-arteom approved these changes

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background-color: #ffffff;
обрати потом внимание на макете. у тебя серый фон #F2F2F2, в него вложен контейнер с белым фоном и тенью box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  position: relative;
body блочный. Тебе это не нужно и не стоит так центровать элементы. У тебя внутри будет div, например класс container. Ему задастся ширина и margin:0 auto. https://up.htmlacademy.ru/htmlcss/34/module/5/item/11

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  top:24px;
тут не нужно абсолютное позиционирование. Это будут флекс или грид-элементы. Когда ты вырываешь элементы из потока, тебе будет очень сложно сделать так, чтобы при изменении контента твоя верстка не разволилась. Эти элементы должны быть в потоке

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  width:160px;
абсолют не нужен, кнопка не выдержит переполнения

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  position: absolute;
не нужно, твоя ссылка размером 0*0, она не работает

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  transform: translateX(-50%);
лучше будет сделать это margin

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  Height: 384px;
свойства с маленькой буквы

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
у этой кнопки вываливается содержимое из нее

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 15px 10px 15px 10px;
этот padding лучше задать родителю

2022-06-03 19:46 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
размер строчных элементов зависит от содержания, линейный размер так не сработает.
задав фону повторение и размер, убережешь себя от проблем в будущем

2022-06-03 19:46 UTC, merged

2022-06-05 09:16 UTC, Danilooo77 commented on styles/styles.css
> +  background-color: #ffffff;
thank you